name: Testing

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Configure
        run: cmake -S . -B build -DTRIE_BUILD_TESTING=ON

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --verbose -j$(nproc) --test-dir build

      - name: Generate coverage reports
        if: matrix.os == 'ubuntu-latest'  # Only generate coverage on Linux for simplicity
        run: |
          sudo apt-get install -y lcov
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.info
          fail_ci_if_error: true