name: Testing

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Configure
        run: cmake -S . -B build -DTRIE_BUILD_TESTING=ON

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --verbose -j$(nproc) --test-dir build

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}